version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-r5ef0472svgp"
s3_prefix = "sam-app"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Repository=\"https://github.com/TomPretty/sam-app\" Branch=\"main\""
